[config]

[templates.hyprland]
input_path = "./templates/hyprlua-colors.lua"
output_path = "~/.config/hypr/colors.lua"

[templates.kitty]
input_path = "./templates/kitty-colors.conf"
output_path = "~/.config/kitty/colors.conf"
pre_hook = "mkdir -p ~/.config/kitty"

[templates.qs]
input_path = "./templates/quickshell-colors.json"
output_path = "~/.config/quickshell/colors.json"
