pragma Singleton
import Quickshell
import qs.components
import QtQuick

Singleton {
  property string chevron_up: ""
  property string chevron_down: ""
  property string chevron_left: ""
  property string chevron_right: ""
  property string battery_full: "󰁹"
  property string battery_90: "󰂂"
  property string battery_80: "󰂁"
  property string battery_70: "󰂀"
  property string battery_60: "󰁿"
  property string battery_50: "󰁾"
  property string battery_40: "󰁽"
  property string battery_30: "󰁼"
  property string battery_20: "󰁻"
  property string battery_10: "󰁺"
  property string battery_empty: "󰂎"
  property string plugged: ""
  property string monitor_speaker: "󰽟"
  property string volume_low: "󰕿"
  property string volume_mid: "󰖀"
  property string volume_high: "󰕾"
  property string volume_muted: "󰸈"
  property string mic: ""
  property string mic_muted: "󰍭"
  property string mic_outline: ""
  property string web_remove: "󰕑"
  property string close: ""
  property string wallpaper: "󰸉"
  property string reload: "󰑓"
  property string power: "󰐥"
  property string user: ""
  property string lock: ""
  property string night_mode: "󰖔"
  property string bluetooth: ""
  property string wifi_str_4: "󰤨"
  property string cpu: ""
  property string ram: ""
  property string sun: ""
  property string moon: ""
  property string gear: ""
  property string gear_filled: ""
  property string gears: ""
  property string dots_v: "󰇙"
  property string dots_h: "󰇘"
  property string clock: ""
  property string chip: "󰘚"
  property string headphone: "󰋋"
  property string soundbar: "󱟛"
  property string phone: ""
  property string message_outline: "󰍥"
  property string message_text: "󰍩"
  property string search: ""
  property string archive: ""
  property string circle_play: ""
  property string terminal: ""
  property string folder: ""
  property string spinner: ""
  property string hypr: ""
  property string quickshell: ""
  property string bluetooth_alt: "󰂯"
  property string bluetooth_alt_connected: "󰂱"
  property string layout: ""
  property string apps: ""
  property string border_top: "󰢦"
  property string border_left: "󰢣"
  property string border_right: "󰢥"
  property string border_bottom: "󰢢"
  property string palette: ""
}
